### ISSUE TITLE
Formatter cannot handle non-ascii characters

### ISSUE THREAD

**Issue by Baughn** [1connect/nginx-config-formatter#2]
E.g. if the config file contains a german "für", it will crash with an encoding error.

See https://github.com/NixOS/nixpkgs/issues/22883

**Comment by slomkowski** [comment]
The problem was caused by file encoded in latin1. I didn't observe the problem with UTF-8 files. I modified the script to do some crude detection of input encoding.

**Comment by Baughn** [comment]
Nginx doesn't have a defined encoding for its config files?

I'm wondering if this might be PEBCAK.

**Comment by slomkowski** [comment]
Haven't heard about it. I just tested: nginx 1.10.3 doesn't mind UTF-8 nor latin1 characters in comments and domain names.
