### ISSUE TITLE
invalid variable name with $

### ISSUE THREAD

**Issue by patsevanton** [1connect/nginx-config-formatter#4]
```
server {
    listen 80 default_server;
    server_name localhost;
    location / {
        proxy_set_header X-User-Authorization "Internal ${cookie_access_token}";
    }
}
```
**nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful**

```
server {
    listen 80 default_server;
    server_name localhost;
    location / {
        proxy_set_header X-User-Authorization "Internal $ {
            cookie_access_token
        }
        ";
    }
}
```
**nginx: [emerg] invalid variable name in /etc/nginx/nginx.conf:63
nginx: configuration file /etc/nginx/nginx.conf test failed**

**Comment by slomkowski** [comment]
I fixed it, sorry for late patch.

**Comment by patsevanton** [comment]
Thanks. Dont Worry :)
