### ISSUE TITLE
Line break when line contains backslash

### ISSUE THREAD

**Issue by kum1ko** [1connect/nginx-config-formatter#5]
eg.

**location ~ /\\.ht {    
    deny all;    
}** 

after formatted will look like this

**location ~ /
\\
.ht {
    deny all;
 #}**

**Comment by vasilevich** [comment]
Hey thanks for reporting I will take a look at it shortly.

**Comment by vasilevich** [comment]
Hey , it seems to not happen at my [nodejs port](https://github.com/vasilevich/nginxbeautifier), maybe 1connect can use my repository to figure out why.
[please try it here](https://nginxbeautifier.com). I don't know python hope JS can be of help [here](https://github.com/vasilevich/nginxbeautifier).

**Comment by slomkowski** [comment]
@kum1ko seems to be fixed now.

**Comment by kum1ko** [comment]
Thanks @slomkowski
